### ISSUE TITLE
`release --pre` should count up patch version

### ISSUE THREAD

**Issue by iigorr** [exaring/release-cli#1]
The --pre flag does not support the usual versioning workflow.

expected

 “0.4.12” => `release -pre` => “0.4.13-RC1" => `release` => “0.4.13”

actual:

“0.4.12” => `release -pre` => “0.4.12-RC1" => `release` => “0.4.13”

**Comment by hikhvar** [comment]
Close due to major rework. This rework closed the bug:
```
% git describe --tags                                            
0.0.50-6-g2ecfa25

% release -d -pre
INFO[0000] Create new releasing version                  Dry=true Repository=foo Tag=v0.0.51-RC1
````
